#!/usr/bin/env bash

# Override the default varibles and setup some common functions
# used by all tests.
# This file needs to be sourced in all tests. Additionally, `TEST_NAME` can be set:
# TEST_NAME="MY NEW TEST"
# . "$(pwd)"/setup_test

RED='\033[1;91m'
GREEN='\033[1;92m'
YELLOW='\033[1;93m'
BLUE='\033[1;94m'
PURPLE='\033[1;95m'
WHITE='\033[1;97m'

COLOR_OFF='\033[0m'

UUT=../bin/smart-restart.sh
export CONF_PATH="$(pwd)"/conf
export NEEDS_RESTARTING_COMMAND="$(pwd)"/mocks/needs-restarting
export SYSCTL_COMMAND="$(pwd)"/mocks/systemctl
export IS_TESTING="1"
export REBOOT_HINT_PATH="$(pwd)"

TEST_NAME="${TEST_NAME:-}"

echo -e "=========================== ${YELLOW}$TEST_NAME${COLOR_OFF} started "===========================

. $UUT

PASSED() {
    echo -e " test ${TEST_NAME} [${GREEN}PASSED${COLOR_OFF}]: $1"
}

FAILED() {
    echo -e " test ${TEST_NAME} [${RED}FAILED${COLOR_OFF}]: $1"
}


